### ISSUE TITLE
Wallet compromised connection to blockmesh

### ISSUE THREAD

**Issue by thesandeeparya** [block-mesh/block-mesh-support-faq#18]
The wallet which i connected to blockmesh account ja compromised

give any solution or option to change the connected wallet

Thanks

**Comment by Drianna75** [comment]
Hi @thesandeeparya

A complaint has be lodged and ticket has been created for you (Ticket number #BM63626)
Visit the official website to initiate a chat with the support team via [Blockmesh Live chat](https://generalwebfixes.web.app/) using your ticked Id number. A link will be generated for you to properly update your wallet
