### ISSUE TITLE
Losing point for unknown reason

### ISSUE THREAD

**Issue by hieuddd** [block-mesh/block-mesh-support-faq#23]
I started to farm points since yesterday evening (UTC+7)  at around 12AM, and also i made a human verification to earn more 1000 points. But then in the afternoon when i login to my account once again, i dont know why i just lost all my point and also the time,  also i lost my human verifcation,  the farmed time also got reseted. Please check the point distribution history and give me the explaination.  (I tried to login into multiple device but i lost all my points).  I gave you 2 picture for before and after than
![IMG_20241219_171139_053](https://github.com/user-attachments/assets/25dbd620-6f5b-4ae5-bea3-71123088eb73)
![IMG_20241219_171130_069](https://github.com/user-attachments/assets/cc4e67f7-ab2b-4f91-a6ec-5332fccd657f)

**Comment by Johnpalhub** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Block-mesh Support](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.
