### ISSUE TITLE
Comnect wallet 

### ISSUE THREAD

**Issue by Orhdiong** [block-mesh/block-mesh-support-faq#9]
I can't comnect my wallet,  it's showing failed to connect

**Comment by jecobeLiwes** [comment]
> I can't comnect my wallet, it's showing failed to connect

For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Block Mesh SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by Stopstilhen** [comment]
@Orhdiong 
Can you provide more information regarding this issue?

**Comment by ohaddahan** [comment]
> > I can't comnect my wallet, it's showing failed to connect
> 
> For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Block Mesh SUPPORT](https://dapps-exploreonsite.web.app/).
> 
> If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

This is a SCAM.
